### ISSUE TITLE
Should `SampleCollection` be used to represent a single sample?

### ISSUE THREAD

**Issue by bbartley** [Bioprotocols/labop#115]
Currently, there does not seem to be a way to represent individual samples in containers like microfuge tubes (or reagents supplied by a vendor in an individual container).  Is it expected to use `SampleCollection` or subclass thereof?  (I think this solution might work in practice, but the semantics are confusing)

**Comment by jakebeal** [comment]
It is intentional that a single sample is represented as a collection with one member. The reason for this is to try to push people towards collection-oriented proposal design (operating on groups and subsets) rather than iterative design (operating on one well at a time)
