### ISSUE TITLE
Refactoring PAML naming to LabOP

### ISSUE THREAD

**Issue by photocyte** [Bioprotocols/labop#162]
Per https://github.com/Bioprotocols/paml/issues/107 & Dan's recent email to the mailing list (https://groups.google.com/g/bioprotocols/c/ijV7jHK5t2w) PAML is being renamed to LabOP.

Clearly there are a lot of places to make this replacement rename, and it might take awhile to be fully accomplished. Here is a short list that can start taking a crack at...

(1) ~~This repo name itself & included documentation~~ **pamled**
(2) ~~The Github landing page (https://github.com/Bioprotocols)~~ (excluding the logo as of 2022-10-18)
(3) ~~The Bioprotocols.org landing page (https://bioprotocols.github.io/paml/ <- note **paml** in URL)~~
(4) Places in code in various repos... ~~"labop" repo~~
(5) ~~Documentation on Open Collective (https://opencollective.com/bioprotocols)~~

**Comment by rpgoldman** [comment]
Suggest we unpack these into individual issues.  The rationale is that if we bundle multiple to-do items into one issue, then it is very hard for us to tell if/when they are done and what remains to do.

Need to carefully maintain all the old pointers, as well.

Not sure *what* to do with the OWL stuff -- we're all just at the mercy of what the various tools can do with redirection/`sameAs`.

**Comment by danbryce** [comment]
I pushed e807e5fb3544fc41b2cb5db7913210f9cfd49bbf, which renames PAML to LabOP.  This take of 1 and 4 (for this repo).

**Comment by danbryce** [comment]
I fixed it.

**Comment by photocyte** [comment]
I believe this is probably completed? Closing if so. Can reopen if not.
