### ISSUE TITLE
[feature request] Adapter for Opentrons Execution

### ISSUE THREAD

**Issue by tsdobbs** [Bioprotocols/labop#87]
We'd like a tool to convert abstract PAML into Opentrons-readable JSON. The most helpful place to start is to mark the spots that will need to change from the version built for Strateos/Autoprotocol

Because the Opentrons API has relatively few primitives (it basically just handles liquids), there should be relatively few mappings required, and I expect that most outputs will only be partially executable on an Opentrons robot. So non-robot-executable steps could be represented as protocol metadata, or in a separate plaintext file.

**Comment by celleleven** [comment]
Hi Tim,

Just to keep you in the loop, the OTB is on track. Here are my notes on the OTB, I still have a lot of revisions to make, I’ll let you know when it's ready to share publicly.

https://github.com/celleleven/Open-Temperature-Block <https://github.com/celleleven/Open-Temperature-Block>


Best,
James

**Comment by tsdobbs** [comment]
> Hi Tim, Just to keep you in the loop, the OTB is on track. Here are my notes on the OTB, I still have a lot of revisions to make, I’ll let you know when it's ready to share publicly. https://github.com/celleleven/Open-Temperature-Block <https://github.com/celleleven/Open-Temperature-Block> Best, James

Thanks James - let's take this in a different thread. Excited to see how it's coming along!
